// Cookies from this list are blocked by default
const defaultSites = {
  'Bloomberg': 'bloomberg.com',
  'Bloomberg Quint': 'bloombergquint.com',
  'Business Insider': 'businessinsider.com',
  'Encyclopedia Britannica': 'britannica.com',
  'Financial Times': 'ft.com',
  'Foreign Policy': 'foreignpolicy.com',
  'Fortune': 'fortune.com',
  'Glassdoor': 'glassdoor.com',
  'Harper\'s Magazine': 'harpers.org',
  'Harvard Business Review': 'hbr.org',
  'Loeb Classical Library': 'loebclassics.com',
  'London Review of Books': 'lrb.co.uk',
  'Medium': 'medium.com',
  'The Athletic UK': 'theathletic.co.uk',
  'The Atlantic': 'theatlantic.com',
  'The Daily Telegraph': 'dailytelegraph.com.au',
  'The Economist': 'economist.com',
  'The New Yorker': 'newyorker.com',
  'The New York Times': 'nytimes.com',
  'The Spectator': 'spectator.co.uk',
  'The Telegraph': 'telegraph.co.uk',
  'The Times': 'thetimes.co.uk',
  'The Wall Street Journal': 'wsj.com',
  'The Washington Post': 'washingtonpost.com',
  'The Wrap': 'thewrap.com',
  'Times Literary Supplement': 'the-tls.co.uk',
  'Vanity Fair': 'vanityfair.com',
  '*General Paywall Bypass*': 'generalpaywallbypass'
};
